### PR TITLE
[Frontend][Issue #70]  Fix dashboard positions when visible

### LINKED ISSUE #70: Fix dashboard positions when visible
Fix the positions of the navbar and sidebar content.

branch: bug/dashboard-positions

### PR DESCRIPTION
**Pull request by vinfante**
Hi @fannypc11 @georgexx009-wizeline 
Here is the pul request for issue #70

- React icons added
- Rename colors:
Previous:   color: var(--rp-text-color-primary) !important;
New:   color: var(--rp-light-text-color-primary) !important;

Previous:   color: var(--rp-text-color-secondary) !important;
New:   color: var(--rp-dark-text-color-secondary) !important;

- Navbar.Toggle changed to React Button
- Depending on the toggle state an icon is displayed
- Navbar.Collpase changed to div: styles added for collapsible opened or closed
- Styles added for sidebar container: opened or closed
- navbar style was renamed to topbar

closes #70

### CODE REVIEW

File: remote_payment_front/src/layouts/Sidebar.jsx [hunk 1]
```diff
@@ -9,11 +11,20 @@ function Sidebar(props) {
...
         <div>
-          <Navbar.Toggle
-            className={`${styles.toggler}`}
+          <Button
             onClick={() => setToggle(!toggle)}
-          />
-          <div className="collapse navbar-collapse" id="navbar-collapse-larr" />
+            className={
+              toggle
+                ? `shadow-none ${styles.toggler} opened`
```
Comment (georgexx009-wizeline) [inline remote_payment_front/src/layouts/Sidebar.jsx:18]: here the shadow-none and the styles.toggler value are being repeat since we only toggle the opened class. We could just apply the ternary to the opened class.
``shadow-none ${styles.toggler} ${toggle ? 'opened' : ''}``
The white space at the end if is false shouldn't affect the code

Comment (JossEsparza) [reply remote_payment_front/src/layouts/Sidebar.jsx]: Fixed with commit:
19d2aae4b1a715845561e5344a945070286ee3d6 [19d2aae]

**Review by georgexx009-wizeline — APPROVED** [review]

**Review by fannypc11 — APPROVED** [review]
